GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order milk"
}

###

DELETE http://localhost:3001/todo/delete/652e9e002ac346f1bc52e303

###

PUT http://localhost:3001/todo/complete/652ea07f374999a50fde1149